stages:
    - verify
    - deploy

PHPCS:PHP7.2:MySQL:
    stage: verify
    image: wpunit/php:wpcs
    script:
        - phpcs

Deploy:
    stage: deploy
    environment: 
        name: deployment
    image: wpunit/php:svn-release
    when: manual
    script:
        - bash bin/gitlab-deploy.sh